server:
  port: 8081
spring:
  application:
    name:  jjmall-goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jjmall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&useAffectedRows=true
    username:  root
    password:  lei11840
mybatis:
  configuration:
    map-underscore-to-camel-case: true
##配置负载均衡